version: '3'

services:

  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appvendas
      MYSQL_USER: appvendas
      MYSQL_PASSWORD: 1234
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3308:3306'
    volumes:
      - './database/data:/var/lib/mysql'
      - './database/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './database/sql:/docker-entrypoint-initdb.d'

  api:
    depends_on: 
      - db
    image: johnny00joe/appvendas-backend
    ports:
      - '8080:8080'

  front:
    depends_on: 
      - api
    image: johnny00joe/appvendas-frontend
    ports:
      - '3000:80'
    


